# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-05 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=5)),
                ('catalog_number', models.IntegerField()),
            ],
            options={
                'ordering': ['catalog_number'],
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_useful', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=100)),
                ('sku', models.IntegerField()),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_required', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Textbooks',
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Textbook'),
        ),
        migrations.AddField(
            model_name='rating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='books',
            field=models.ManyToManyField(to='core.Textbook'),
        ),
    ]
