# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-05 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170205_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='used_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
