# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-05 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='catalog_number',
            field=models.CharField(max_length=5),
        ),
    ]
